name: Enforce Version Bump

on:
  pull_request:
    branches:
      - main

jobs:
  check_version_bump:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get PR commit messages
        id: check_commits
        run: |
          echo "Checking commit messages in PR..."
          COMMITS=$(git log --pretty=format:%s origin/main..HEAD)
          echo "$COMMITS"

          if echo "$COMMITS" | grep -q "#major"; then
            exit 0
          elif echo "$COMMITS" | grep -q "#minor"; then
            exit 0
          elif echo "$COMMITS" | grep -q "#patch"; then
            exit 0
          else
            echo "❌ ERROR: No version bump tag (#major, #minor, or #patch) found in PR commits!"
            exit 1
          fi
